### PR TITLE
fix(tailwind): render single tags

### LINKED ISSUE #215: Bug: `<br />` within `<p></p>` creates additional `<br />` at the end
Input:

```html
<p>
  a<br />
  b<br />
  c<br />
  d
</p>
```

Output:
```html
<p>
  a
   <br>
  b
   <br>
  c
   <br>
  d
   <br>
   <br>
   <br>
</p>
```

### PR DESCRIPTION
**Pull request by kabarchonok**
resolves: https://github.com/vue-email/vue-email/issues/215

### CODE REVIEW

**Comment by Flowko** [comment]
hi, thanks for taking the time to check this one out, i just need to know if this will work fine in serverless envirments, is that library supported and works as expected there ?

**Comment by Flowko** [comment]
nvm, just tested it, works as expected, will merge, thank you

**Review by Flowko — APPROVED** [review]

**Comment by MickL** [comment]
May you explain what you changed exactly @kabarchonok ?

i see a lot in the package.json but because it has been reordered I am not exactly sure what you did exactly to fix this :)

**Comment by Flowko** [comment]
@MickL only one package was added, `domhandler` it got reordered so thats why

**Pull request merged**
