### PR TITLE
[FEATURE] i18n support

### PR DESCRIPTION
**Pull request by Dave136**
The goal is provide support for i18n, adding translations for the template.

- [x] Extends option types adding i18n config object
- [x] Import and usage of library
- [x] Add i18n for compiler
- [x] Add i18n support for normal render
- [x] Add test
- [x] Update docs
- ~~[ ] Add nuxt support~~ ( cant fix, nuxt playground needs a rewrite to use the server render instead of using component render )

### CODE REVIEW

**Comment by xlanex6** [comment]
Hi @Dave136 , @Flowko 

I use this package in production for my client Nuxt app. 

It seems close to the end about this feature , expect doc. 

How I can help to fininalise this PR to push this feature into the main package ?
I currently deal with i18n /nuxt / and compile but on dirty way ....

I will clean code after PR validate .

Regards

**Comment by Flowko** [comment]
hi @xlanex6 , me and Dave are a bit busy with full time jobs, and sorry to delay these features, but i believe there's only one issue left with this integration, related to nuxt not handeling `$t('shortname', ...data)` correctly, ill try to look into it and see if i can fix.

**Comment by xlanex6** [comment]
I understand 
yes i use the v8 version of the module i18n 

looking forwards guys

**Review by Flowko — APPROVED** [review]

**Comment by Flowko** [comment]
@xlanex6  its live, please upgrade to version `0.7.0`, bare in made its still rough arround the edges and some of the `vue-i18n` functionalities are not working like `Interpolations` ..., 
but the basic stuff like translating text should work fine
if u find any issues let us know

**Comment by xlanex6** [comment]
Thanks @Flowko 
Great job 
I will implement this soon end report bug if so.

Well done for you job guy
email + nuxt + vue IS 🧁

**Pull request merged**
